name: "Validate Input and Call API"
description: "Validates input JSON and calls an API if valid"

runs:
  using: "composite"
  steps:
    - name: Hello world action
      run: |
        echo "$GITHUB_CONTEXT"