name: "Validate Input and Call API"
description: "Validates input JSON and calls an API if valid"
inputs:
  repository_name:
    description: 'Repository name'
    required: true
  version:
    description: 'Version'
    required: true
  input-data:
    description: "The input data in JSON format"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository 2
      uses: actions/checkout@v4
      with:
          repository: MonikaSinghal-22/Repo2-action-test  # Repo2's name
          ref: v1.8  # The specific tag or branch you want to use in Repo2

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Data Lookup - repo name
      run: echo '${{ inputs.repository_name}}'
      shell: bash

    - name: Data Lookup - version
      run: echo '${{ inputs.version }}'
      shell: bash

    - name: Data Lookup - sbom
      run: echo '${{ inputs.input-data}}'
      shell: bash

    - name: Write Input to File
      run: echo '${{ inputs.input-data }}' > input.json
      shell: bash

    - name: List files for debugging
      run: |
        echo "Listing files in the current directory:"
        ls -R  # List all files recursively to see the directory structure
      shell: bash

    - name: Validate Input
      run: python validate.py
      shell: bash

    - name: Print Input JSON
      run: cat input.json  # Print input.json before calling the API
      shell: bash

    - name: Call API (Only if Validation Passes)
      run: |
        echo "✅ Calling API..."
        curl -X POST https://example.com/api --data @input.json
      shell: bash
