name: "Validate Input and Call API"
description: "Validates input JSON and calls an API if valid"

inputs:
  repository_name:
    description: 'Repository name'
    required: false
  version:
    description: 'Version'
    required: true
  user:
    description: 'user'
    required: true
  input-data:
    description: "JSON input data"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --repository_name=${{ inputs.repository_name }}
    - --version=${{ inputs.version }}
    - --user=${{ inputs.user }}
    - --input_data=${{ inputs.input-data }}
    - --base_url=${{ vars.BASE_URL || "https:test.com" }}
