name: "Validate Input and Call API"
description: "Validates input JSON and calls an API if valid"

runs:
  using: "composite"
  steps:
    - name: Hello world action
      # with: # Set the secret as an input
      #   super_secret: ${{ secrets.BASE_API_URL }}
      env: # Or as an environment variable
        super_secret: ${{ secrets.BASE_API_URL }}