name: "Validate Input and Call API"
description: "Validates input JSON and calls an API if valid"
inputs:
  repository_name:
    description: 'Repository name'
    required: true
    default: ''
  version:
    description: 'Version'
    required: true
    default: '0.0.1'
  input-data:
    description: "The input data in JSON format"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository 2
      uses: actions/checkout@v4
      with:
          repository: MonikaSinghal-22/Repo2-action-test  # Repo2's name
          ref: v1.12  # The specific tag or branch you want to use in Repo2

    - name: Set Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check Repository Name
      id: check_repo
      run: |
        if [ -z "${{ inputs.repo_name }}" ]; then
          echo "repo_name is empty. Assigning to github.repository."
          echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
        else
          echo "repo_name is provided: ${{ inputs.repo_name }}"
          echo "REPO_NAME=${{ inputs.repo_name }}" >> $GITHUB_ENV
        fi
      shell: bash

    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq curl
      shell: bash

    - name: Format JSON Data
      run: |
        echo '{
          "release": {
            "repo_name": "${{ env.REPO_NAME }}",
            "version": "${{ inputs.version }}",
            "user": $(echo '${{ inputs.user_data }}' | jq -c '.user'),
            "data": $(echo '${{ inputs.user_data }}' | jq -c '.data')
          }
        }' | jq . > formatted_data.json
      shell: bash

    - name: Print Formatted JSON
      run: cat formatted_data.json
      shell: bash

    - name: List files for debugging
      run: |
        echo "Listing files in the current directory:"
        ls -R  # List all files recursively to see the directory structure
      shell: bash

    - name: Validate Input
      run: python validate.py
      shell: bash

    # - name: Call API (Only if Validation Passes)
    #   run: |
    #     echo "✅ Calling API..."
    #     curl -X POST https://example.com/api --data @input.json
    #   shell: bash
