name: API Workflow

on:
    workflow_call:
        inputs:
            repository_name:
                description: 'Repository name'
                required: false
                type: string
            user:
                description: 'user'
                required: true
                type: string
            version:
                description: 'Version'
                required: true
                type: string
            input-data:
                description: "JSON input data"
                required: true
                type: string

env:
    BASE_API_URL: http://test.com

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Show inputs
        run: |
          echo "Repo: ${{ inputs.repository_name }}"
          echo "User: ${{ inputs.user }}"
          echo "Version: ${{ inputs.version }}"
          echo "Input: ${{ inputs['input-data'] }}"

# jobs:
#     call-api-action:
#         name: Use Repository 2 Action 
#         uses: MonikaSinghal-22/Repo2-action-test@v1.43  # Replace 'author/repository2' with your GitHub repo path
#         with:
#             repository_name: ${{ github.repository}}
#             user: ${{ github.actor }}
#             version: ${{ inputs.version }}
#             input-data: ${{ inputs.input-data }}
#             base-api-url: ${{ env.BASE_API_URL }}
