name: V
on:
    workflow_call:

jobs:
    checkrepo:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4

            - name: checkout v repo
              uses: actions/checkout@v4
              with:
                repository: MonikaSinghal-22/Repo2-action-test
                ref: master
                path: v-repo

            - name: Repo name
              run: echo "${{github.repository}}"

            - name: see values
              run: |
                python3 v-repo/scripts/v_config_processor.py
