name: Validate Input & Call API

on:
  repository_dispatch:
    types: [validate-and-call-api]
  workflow_dispatch:

jobs:
  validate-and-call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Create Input JSON File
        run: |
          echo '${{ toJson(github.event.client_payload) }}' > input.json

      - name: Validate Input with Python
        id: validate
        run: python validate.py

      - name: Call External API
        if: success()
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://example.com/api/endpoint"
          method: "POST"
          customHeaders: '{"Content-Type": "application/json"}'
          body: '{"user": "${{ env.USER }}", "data": "${{ env.DATA }}"}'
